const theme=document.createElement('link');theme.rel='stylesheet';theme.href='css/theme.css';document.head.appendChild(theme);const favicon=document.createElement('link');favicon.rel='icon';favicon.type='image/svg+xml';favicon.href='assets/testyourself-icon.svg';document.head.appendChild(favicon);

const state={grade:'Year 5',path:'Learn & Practice'};
const gradePills=[...document.querySelectorAll('#gradePills button')],pathCards=[...document.querySelectorAll('.path-card')],gradeCards=[...document.querySelectorAll('[data-grade-card]')],selectedPath=document.getElementById('selectedPath'),continueBtn=document.getElementById('continueBtn'),toast=document.getElementById('toast'),menuBtn=document.querySelector('.menu-btn'),mainNav=document.querySelector('.main-nav'),navCta=document.querySelector('.nav-cta');
const profile=(()=>{try{return JSON.parse(localStorage.getItem('tyProfile')||'null')}catch(e){return null}})();
function gradeCode(g){if(g==='Kindergarten')return'K';return String(g).replace('Year ','')}
function gatedUrl(url,grade){return profile?url:`register.html?grade=${encodeURIComponent(gradeCode(grade||state.grade))}`}
function updateSelection(){selectedPath.textContent=`${state.grade} · ${state.path}`}
function selectGrade(grade){state.grade=grade;gradePills.forEach(button=>{const active=button.dataset.grade===grade;button.classList.toggle('active',active);button.setAttribute('aria-pressed',active?'true':'false')});updateSelection()}
function selectPath(path){state.path=path;pathCards.forEach(button=>{const active=button.dataset.path===path;button.classList.toggle('active',active);button.setAttribute('aria-pressed',active?'true':'false')});updateSelection()}
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),3000)}
if(navCta){if(profile){navCta.textContent='Continue practice';navCta.href=`practice.html?grade=${encodeURIComponent(profile.grade||'5')}`}else{navCta.textContent='Register free';navCta.href='register.html'}}
gradePills.forEach(button=>button.addEventListener('click',()=>selectGrade(button.dataset.grade)));pathCards.forEach(button=>button.addEventListener('click',()=>selectPath(button.dataset.path)));
gradeCards.forEach(card=>{card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label',`Choose ${card.dataset.gradeCard}`);const choose=()=>{selectGrade(card.dataset.gradeCard);document.getElementById('quick-start').scrollIntoView({behavior:'smooth'})};card.addEventListener('click',choose);card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();choose()}})});
continueBtn.addEventListener('click',()=>{const code=gradeCode(state.grade);if(state.path==='Test Preparation'){showToast('Test preparation pathways are being added next. Choose Learn & Practice or Mixed Challenge for free practice now.');return}window.location.href=profile?`practice.html?grade=${encodeURIComponent(code)}`:`register.html?grade=${encodeURIComponent(code)}`});
function connectTopic(name,url,grade='Year 5'){const card=[...document.querySelectorAll('.topic-card')].find(c=>c.querySelector('h3')?.textContent.includes(name));if(!card)return;card.style.cursor='pointer';card.tabIndex=0;const go=()=>window.location.href=gatedUrl(url,grade);card.addEventListener('click',go);card.addEventListener('keydown',e=>{if(e.key==='Enter')go()})}
connectTopic('Fractions','YR5/fractions.html','Year 5');connectTopic('Problem Solving','word-problems.html','Year 5');connectTopic('Maths Fluency',`practice.html?grade=${profile?.grade||'5'}`,'Year 5');
document.querySelectorAll('[data-test]').forEach(button=>button.addEventListener('click',()=>{const test=button.dataset.test;state.path='Test Preparation';if(test.includes('NAPLAN'))state.grade='Year 5';if(test.includes('Opportunity'))state.grade='Year 4';if(test.includes('Selective'))state.grade='Year 6';selectGrade(state.grade);selectPath(state.path);showToast(`${test} pathway is planned next. Free year-level practice is available now.`)}));
menuBtn.addEventListener('click',()=>{const open=mainNav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open?'true':'false');menuBtn.textContent=open?'×':'☰'});mainNav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{mainNav.classList.remove('open');menuBtn.setAttribute('aria-expanded','false');menuBtn.textContent='☰'}));updateSelection();