const state = { grade: "Year 5", path: "Learn & Practice" };
const gradePills=[...document.querySelectorAll("#gradePills button")],pathCards=[...document.querySelectorAll(".path-card")],gradeCards=[...document.querySelectorAll("[data-grade-card]")],selectedPath=document.getElementById("selectedPath"),continueBtn=document.getElementById("continueBtn"),toast=document.getElementById("toast"),menuBtn=document.querySelector(".menu-btn"),mainNav=document.querySelector(".main-nav");
function updateSelection(){selectedPath.textContent=`${state.grade} · ${state.path}`}
function selectGrade(grade){state.grade=grade;gradePills.forEach(b=>{const a=b.dataset.grade===grade;b.classList.toggle("active",a);b.setAttribute("aria-pressed",a)});updateSelection()}
function selectPath(path){state.path=path;pathCards.forEach(b=>{const a=b.dataset.path===path;b.classList.toggle("active",a);b.setAttribute("aria-pressed",a)});updateSelection()}
function showToast(m){toast.textContent=m;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),3000)}
gradePills.forEach(b=>b.addEventListener("click",()=>selectGrade(b.dataset.grade)));pathCards.forEach(b=>b.addEventListener("click",()=>selectPath(b.dataset.path)));
gradeCards.forEach(card=>{card.tabIndex=0;card.setAttribute("role","button");card.setAttribute("aria-label",`Choose ${card.dataset.gradeCard}`);const choose=()=>{selectGrade(card.dataset.gradeCard);document.getElementById("quick-start").scrollIntoView({behavior:"smooth"})};card.addEventListener("click",choose);card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();choose()}})});
continueBtn.addEventListener("click",()=>{if(state.grade==="Year 5"&&state.path==="Learn & Practice")window.location.href="YR5/fractions.html";else showToast(`${state.grade} · ${state.path} selected. More learning modules are being added.`)});
const fractionCard=[...document.querySelectorAll(".topic-card")].find(c=>c.querySelector("h3")?.textContent.includes("Fractions"));if(fractionCard){fractionCard.style.cursor="pointer";fractionCard.tabIndex=0;fractionCard.addEventListener("click",()=>window.location.href="YR5/fractions.html");fractionCard.addEventListener("keydown",e=>{if(e.key==="Enter")window.location.href="YR5/fractions.html"})}
document.querySelectorAll("[data-test]").forEach(button=>button.addEventListener("click",()=>{const test=button.dataset.test;state.path="Test Preparation";if(test.includes("NAPLAN"))state.grade="Year 5";if(test.includes("Opportunity"))state.grade="Year 4";if(test.includes("Selective"))state.grade="Year 6";selectGrade(state.grade);selectPath(state.path);showToast(`${test} selected. Practice modules will be connected to this pathway.`)}));
menuBtn.addEventListener("click",()=>{const open=mainNav.classList.toggle("open");menuBtn.setAttribute("aria-expanded",open);menuBtn.textContent=open?"×":"☰"});mainNav.querySelectorAll("a").forEach(link=>link.addEventListener("click",()=>{mainNav.classList.remove("open");menuBtn.setAttribute("aria-expanded","false");menuBtn.textContent="☰"}));updateSelection();