const raw=localStorage.getItem('tyProfile');if(!raw){location.replace('register.html');throw Error('Registration required')}
const profile=JSON.parse(raw),$=id=>document.getElementById(id),p=new URLSearchParams(location.search);let grade=p.get('grade')||profile.grade||'2',topic='number',questions=[],idx=0,selected=null,score=0,attempted=0,completed=new Set();
const cfg={K:{max:10,label:'Kindergarten'},1:{max:20,label:'Year 1'},2:{max:1000,label:'Year 2'},3:{max:500,label:'Year 3'},4:{max:1000,label:'Year 4'},5:{max:10000,label:'Year 5'},6:{max:100000,label:'Year 6'}};
const base=[['addition','+','Addition','Add numbers with confidence'],['subtraction','−','Subtraction','Find the difference'],['multiplication','×','Multiplication','Equal groups and facts'],['division','÷','Division','Sharing and grouping'],['number','123','Number Sense','Place value and comparison'],['mixed','⚡','Mixed Challenge','Use different maths skills']];
const y2=[
['number','123','Number & Place Value','Hundreds, tens, ones and number forms'],['compare','<>','Compare & Order','Greater than, less than, number lines and ordering'],['skipcount','↗','Skip Counting','Forward and backward by 2s, 5s, 10s and 100s'],['estimation','≈','Estimation','Estimate quantities and choose reasonable answers'],['evenodd','2·4','Even & Odd','Pairs, equal groups and odd/even numbers'],['basicfacts','★','Basic Facts','Fast addition and subtraction facts'],['doubles','2×','Doubles & Near Doubles','Use doubles to add quickly'],['make10','10','Make a Ten','Bridge through 10 to add and subtract'],['addition','+','Addition','Mental addition and number strategies'],['addition2','+','2-Digit Addition','Split, compensate and regroup'],['addmulti','+++','3 & 4 Addends','Add several numbers efficiently'],['subtraction','−','Subtraction','Count back, difference and mental strategies'],['subtraction2','−','2-Digit Subtraction','Split, regroup and find differences'],['addsub','↔','Addition & Subtraction','Fact families and inverse operations'],['addition3','3D+','3-Digit Addition','Add hundreds, tens and ones'],['subtraction3','3D−','3-Digit Subtraction','Subtract and regroup across places'],['patterns','◆','Patterns','Repeating and growing patterns'],['equations','=','Equations & Equality','True/false, missing numbers and balance'],['multistep','2→','Multi-Step Problems','Solve two-step addition and subtraction problems'],['equalgroups','●●','Equal Groups','Build groups and repeated addition'],['multiplication','×','Multiplication','2s, 3s, 5s and 10s facts'],['division','÷','Division','Sharing and grouping equally'],['fractions','½','Fractions','Halves, thirds, quarters and equal shares'],['money','$','Money','Australian coins, totals and change'],['time','◷','Time','5-minute intervals, quarter hours and duration'],['ampm','AM','A.M. & P.M.','Choose sensible times of day'],['calendar','▣','Calendar','Days, weeks, months and dates'],['length','cm','Length','Centimetres, metres, estimates and comparisons'],['area','▦','Area','Covering and grid area'],['mass','⚖','Mass','Heavier, lighter and measuring'],['capacity','◫','Capacity & Volume','Compare, estimate and measure'],['shapes2d','△','2D Shapes','Sides, vertices, symmetry and sorting'],['shapes3d','▣','3D Objects','Faces, vertices, curved and flat surfaces'],['partition','▥','Partition Shapes','Halves, thirds and quarters of rectangles'],['position','⌖','Position','Directions, paths, turns and grids'],['data','▥','Data','Tables, tallies and simple graphs'],['picturegraph','●','Picture Graphs','Read keys and compare categories'],['bargraph','▤','Bar Graphs','Read bars, totals and differences'],['chance','?','Chance','Likely, unlikely and impossible'],['mixed','⚡','Mixed Challenge','Questions from across the full Year 2 course']];
function rnd(a,b){return Math.floor(Math.random()*(b-a+1))+a}function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function unique(a){return [...new Set(a.map(String))]}function numericChoices(ans,step=1){let vals=[ans],tries=0;while(unique(vals).length<4&&tries++<30){let v=ans+(Math.random()<.5?-1:1)*rnd(1,4)*step;if(v>=0)vals.push(v)}return shuffle(unique(vals)).map(v=>Number(v))}function q(text,answer,opts,tip){let choices=opts?shuffle(unique(opts).map(v=>typeof v==='number'?v:String(v))):numericChoices(answer);if(!choices.some(v=>String(v)===String(answer)))choices[0]=answer;return{text,answer,choices:shuffle(choices),tip}}function wordNumber(n){const ones=['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen'],tens=['','','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety'];if(n<20)return ones[n];if(n<100)return tens[Math.floor(n/10)]+(n%10?' '+ones[n%10]:'');return ones[Math.floor(n/100)]+' hundred'+(n%100?' '+wordNumber(n%100):'')}
function y2q(t){let a,b,c,n;if(t==='mixed')t=y2[rnd(0,y2.length-2)][0];switch(t){
case'number':{let mode=rnd(0,4),n=rnd(100,999),h=Math.floor(n/100),te=Math.floor(n/10)%10,o=n%10;if(mode===0)return q(`What is the value of the ${h} in ${n}?`,h*100,numericChoices(h*100,100),'A digit in the hundreds place is worth hundreds.');if(mode===1)return q(`Which expanded form shows ${n}?`,`${h*100} + ${te*10} + ${o}`,[`${h*100} + ${te*10} + ${o}`,`${h*10} + ${te*100} + ${o}`,`${h*100} + ${te} + ${o*10}`,`${n-1} + 1`],'Break the number into hundreds, tens and ones.');if(mode===2)return q(`Which number is ${h} hundreds, ${te} tens and ${o} ones?`,n,numericChoices(n,10),'Build the number from place values.');if(mode===3)return q(`Which is the word form of ${n}?`,wordNumber(n),[wordNumber(n),wordNumber(Math.max(100,n-10)),wordNumber(Math.min(999,n+100)),wordNumber(Math.max(100,n-100))],'Read hundreds first, then tens and ones.');return q(`10 tens is the same as how many hundreds?`,1,[1,2,10,100],'10 tens = 100 = 1 hundred.')}
case'compare':{a=rnd(100,999);b=rnd(100,999);let mode=rnd(0,2);if(mode===0)return q(`Which symbol makes this true? ${a} □ ${b}`,a>b?'>':a<b?'<':'=',['>','<','='],'Compare hundreds first, then tens, then ones.');if(mode===1){let vals=shuffle([rnd(100,999),rnd(100,999),rnd(100,999)]),ans=[...vals].sort((x,y)=>x-y).join(', ');return q(`Which list is ordered from least to greatest?`,ans,[ans,[...vals].sort((x,y)=>y-x).join(', '),vals.join(', '),[...vals].reverse().join(', ')],'Start with the smallest hundreds value.')}return q(`Which number is greater? ${a} or ${b}`,Math.max(a,b),[a,b],'Compare digits from left to right.')}
case'skipcount':{let step=[2,5,10,100][rnd(0,3)],start=step===100?rnd(1,7)*100:step===10?rnd(1,9):rnd(0,30),dir=Math.random()<.75?1:-1;if(dir<0&&start<step*4)start=step*5;let seq=[0,1,2,3,4].map(i=>start+dir*step*i),m=rnd(1,3),ans=seq[m],shown=seq.map((v,i)=>i===m?'?':v).join(', ');return q(`Complete the sequence: ${shown}`,ans,numericChoices(ans,step),`Count ${dir>0?'forward':'backward'} by ${step}s.`)}
case'estimation':{let actual=rnd(12,97),opts=[10,20,30,50,75,100],ans=opts.reduce((x,y)=>Math.abs(y-actual)<Math.abs(x-actual)?y:x);return q(`A jar looks like it has about ${actual} counters. Which friendly number is the closest estimate?`,ans,shuffle([ans,...opts.filter(x=>x!==ans).slice(0,3)]),'Choose a nearby friendly number, not an exact count.')}
case'evenodd':{n=rnd(1,100);if(Math.random()<.5)return q(`Is ${n} even or odd?`,n%2===0?'Even':'Odd',['Even','Odd'],'Even numbers can be split into 2 equal groups with none left over.');return q(`Which number is even?`,2*a,[2*(a=rnd(2,20)),2*rnd(2,20)+1,2*rnd(2,20)+1,2*rnd(2,20)+1],'Even numbers end in 0, 2, 4, 6 or 8.')}
case'basicfacts':{if(Math.random()<.5){a=rnd(1,10);b=rnd(1,10);return q(`${a} + ${b} = ?`,a+b,null,'Use a fact you know, count on, or make 10.')}a=rnd(8,20);b=rnd(1,a);return q(`${a} − ${b} = ?`,a-b,null,'Think about the related addition fact.')}
case'doubles':{a=rnd(2,10);if(Math.random()<.6)return q(`${a} + ${a} = ?`,a+a,null,`This is a double: ${a} + ${a}.`);return q(`${a} + ${a+1} = ?`,2*a+1,null,`Use the double ${a}+${a}, then add 1.`)}
case'make10':{a=rnd(6,9);b=rnd(3,9);if(Math.random()<.55)return q(`${a} + ${b} = ?`,a+b,null,`Make 10 first: ${a} needs ${10-a} more.`);n=rnd(11,18);b=rnd(3,9);return q(`${n} − ${b} = ?`,n-b,null,'Subtract to 10 first, then subtract what is left.')}
case'addition':a=rnd(5,70);b=rnd(2,30);return q(`${a} + ${b} = ?`,a+b,null,'Split tens and ones or count on efficiently.');
case'addition2':{a=rnd(20,79);b=rnd(11,69);let mode=rnd(0,2);if(mode===0)return q(`${a} + ${b} = ?`,a+b,null,'Add ones, regroup if needed, then add tens.');if(mode===1){let comp=10-a%10;return q(`Use compensation: ${a} + ${b}. If you add ${comp} to ${a} to make ${a+comp}, what should you subtract from the other addend?`,comp,[comp,comp+1,Math.max(0,comp-1),10-comp],'Whatever you add to one addend must be balanced in the other.')}return q(`Break apart ${a} + ${b}. Which expression has the same value?`,`${Math.floor(a/10)*10} + ${a%10} + ${Math.floor(b/10)*10} + ${b%10}`,[`${Math.floor(a/10)*10} + ${a%10} + ${Math.floor(b/10)*10} + ${b%10}`,`${a} + ${b+10}`,`${a-10} + ${b}`,`${Math.floor(a/10)} + ${a%10} + ${Math.floor(b/10)} + ${b%10}`],'Split each addend into tens and ones.')}
case'addmulti':{let count=rnd(3,4),vals=Array.from({length:count},()=>rnd(1,20)),ans=vals.reduce((x,y)=>x+y,0);return q(`${vals.join(' + ')} = ?`,ans,null,'Look for pairs that make 10 or another friendly number.')}
case'subtraction':a=rnd(15,99);b=rnd(1,a);return q(`${a} − ${b} = ?`,a-b,null,'Count back, count up, or split the number you subtract.');
case'subtraction2':{a=rnd(40,99);b=rnd(11,a-1);let mode=rnd(0,2);if(mode===0)return q(`${a} − ${b} = ?`,a-b,null,'Regroup a ten when the ones digit is too small.');if(mode===1)return q(`What addition fact can check ${a} − ${b}?`,`${a-b} + ${b} = ${a}`,[`${a-b} + ${b} = ${a}`,`${a+b} − ${b} = ${b}`,`${a} + ${b} = ${a-b}`,`${a-b} − ${b} = ${a}`],'Difference + subtracted amount should equal the starting number.');return q(`How much more is ${a} than ${b}?`,a-b,null,'“How much more” asks for the difference.')}
case'addsub':{a=rnd(3,18);b=rnd(2,12);n=a+b;return q(`If ${a} + ${b} = ${n}, which related fact is also true?`,`${n} − ${a} = ${b}`,[`${n} − ${a} = ${b}`,`${n} + ${a} = ${b}`,`${a} − ${b} = ${n}`,`${b} − ${n} = ${a}`],'Addition and subtraction undo each other.')}
case'addition3':{a=rnd(100,599);b=rnd(100,399);return q(`${a} + ${b} = ?`,a+b,null,'Add ones, tens, then hundreds. Regroup where needed.')}
case'subtraction3':{a=rnd(300,999);b=rnd(100,a-1);return q(`${a} − ${b} = ?`,a-b,null,'Work from ones to hundreds and regroup when needed.')}
case'patterns':{let mode=rnd(0,2);if(mode===0){let step=rnd(2,10),s=rnd(1,20),seq=[s,s+step,s+2*step,s+3*step],ans=s+4*step;return q(`What comes next? ${seq.join(', ')}, ?`,ans,numericChoices(ans,step),`The rule is add ${step}.`)}if(mode===1)return q('What is the repeating core in: red, blue, blue, red, blue, blue, ...','red, blue, blue',['red, blue, blue','red, blue','blue, blue, red, blue','red, red, blue'],'The core is the smallest part that repeats.');let s=rnd(2,10);return q(`Find the missing number: ${s}, ${s+3}, ?, ${s+9}, ${s+12}`,s+6,numericChoices(s+6,3),'Look for a constant increase.')}
case'equations':{let mode=rnd(0,2),x=rnd(2,20),y=rnd(1,15);if(mode===0){let total=x+y;return q('Which equation is true?',`${x} + ${y} = ${total}`,[`${x} + ${y} = ${total}`,`${x} + ${y} = ${total+1}`,`${total} = ${x-y}`,`${x} = ${total+y}`],'Both sides of = must have the same value.')}if(mode===1){let rhs=x+y;return q(`Find □: □ + ${y} = ${rhs}`,x,numericChoices(x),'Think of the equals sign as a balance.')}let left=x+y,rightA=rnd(1,left-1),rightB=left-rightA;return q(`${x} + ${y} = ${rightA} + ${rightB}`,'True',['True','False'],'Calculate both sides before deciding.')}
case'multistep':{a=rnd(10,40);b=rnd(5,25);c=rnd(3,Math.min(20,a+b));return q(`A class collected ${a} cans on Monday and ${b} on Tuesday. They used ${c} for a project. How many cans are left?`,a+b-c,null,'First add what was collected, then subtract what was used.')}
case'equalgroups':{let groups=rnd(2,6),each=rnd(2,8),total=groups*each;if(Math.random()<.5)return q(`${groups} equal groups have ${each} objects in each group. How many objects altogether?`,total,null,'Repeated addition: add the same group again and again.');return q(`${total} objects are arranged into groups of ${each}. How many equal groups are there?`,groups,null,'Count how many groups of the same size fit.')}
case'multiplication':a=[2,3,5,10][rnd(0,3)];b=rnd(1,10);return q(`${b} × ${a} = ?`,a*b,null,'Use skip counting or repeated addition.');
case'division':b=[2,3,5,10][rnd(0,3)];a=rnd(1,8);n=a*b;return q(`${n} objects are shared equally into ${a} groups. How many in each group?`,b,null,'Equal sharing is division.');
case'fractions':{let den=[2,3,4][rnd(0,2)],mode=rnd(0,2);if(mode===0)return q(`A whole is split into ${den} equal parts. What is each part called?`,den===2?'a half':den===3?'a third':'a quarter',[den===2?'a half':den===3?'a third':'a quarter','a whole','a fifth','an unequal part'],'Equal parts have the same size.');if(mode===1){let total=den*rnd(2,6);return q(`What is 1/${den} of ${total}?`,total/den,null,`Share ${total} into ${den} equal groups.`)}return q(`How many ${den===2?'halves':den===3?'thirds':'quarters'} make one whole?`,den,[2,3,4,den],'A whole contains exactly the denominator number of equal parts.')}
case'money':{let coins=[5,10,20,50,100,200],counts=Array.from({length:3},()=>rnd(0,3)),sel=shuffle(coins).slice(0,3),total=sel.reduce((s,v,i)=>s+v*counts[i],0);if(total===0){counts[0]=1;total=sel[0]}if(Math.random()<.6){let desc=sel.map((v,i)=>`${counts[i]} × ${v>=100?'$'+v/100:v+'c'}`).join(', ');return q(`What is the total value of: ${desc}?`,total>=100?`$${(total/100).toFixed(2)}`:`${total}c`,[total>=100?`$${(total/100).toFixed(2)}`:`${total}c`,`${Math.max(0,total-10)}c`,`${total+20}c`,`$${(total/100+1).toFixed(2)}`],'Add the value of each coin, not just the number of coins.')}a=rnd(5,20);b=rnd(1,a);return q(`You have $${a}. You spend $${b}. How much is left?`,`$${a-b}`,[`$${a-b}`,`$${a+b}`,`$${b}`,`$${a}`],'Subtract the amount spent from the starting amount.')}
case'time':{let h=rnd(1,12),m=[0,5,10,15,20,25,30,35,40,45,50,55][rnd(0,11)],digital=`${h}:${String(m).padStart(2,'0')}`;if(Math.random()<.65)return q(`Which time is ${m} minutes past ${h}?`,digital,[digital,`${h}:${String((m+5)%60).padStart(2,'0')}`,`${h}:30`,`${h}:45`],'Count around a clock in 5-minute steps.');let add=[5,10,15,30][rnd(0,3)],total=h*60+m+add,nh=Math.floor(total/60)%12||12,nm=total%60;return q(`It is ${digital}. What time will it be ${add} minutes later?`,`${nh}:${String(nm).padStart(2,'0')}`,[`${nh}:${String(nm).padStart(2,'0')}`,`${h}:${String(m).padStart(2,'0')}`,`${h}:00`,`${nh}:30`],'Move forward by the given number of minutes.')}
case'ampm':{let items=[['eating breakfast','a.m.'],['going to school in the morning','a.m.'],['eating dinner','p.m.'],['going to bed at night','p.m.'],['watching the sunrise','a.m.'],['seeing the sunset','p.m.']],x=items[rnd(0,items.length-1)];return q(`You are ${x[0]}. Is the time more likely a.m. or p.m.?`,x[1],['a.m.','p.m.'],'a.m. is before noon; p.m. is after noon.')}
case'calendar':{const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],months=['January','February','March','April','May','June','July','August','September','October','November','December'];let mode=rnd(0,2);if(mode===0){let i=rnd(0,6),ans=days[(i+1)%7];return q(`What day comes after ${days[i]}?`,ans,[ans,days[(i+2)%7],days[(i+6)%7],days[(i+3)%7]],'There are 7 days in a week.')}if(mode===1){let i=rnd(0,11),ans=months[(i+1)%12];return q(`Which month comes after ${months[i]}?`,ans,[ans,months[(i+2)%12],months[(i+11)%12],months[(i+6)%12]],'There are 12 months in a year.')}return q('How many days are in one week?',7,[5,6,7,10],'A week has 7 days.')}
case'length':{let mode=rnd(0,2);if(mode===0){a=rnd(10,90);b=rnd(5,50);return q(`A ribbon is ${a} cm long and another is ${b} cm long. What is their total length?`,`${a+b} cm`,[`${a+b} cm`,`${Math.abs(a-b)} cm`,`${a} cm`,`${b} cm`],'Add the two lengths and keep the unit.')}if(mode===1){a=rnd(20,100);b=rnd(10,a-1);return q(`How much longer is ${a} cm than ${b} cm?`,`${a-b} cm`,[`${a-b} cm`,`${a+b} cm`,`${b} cm`,`${a} cm`],'Subtract to find the difference in length.')}return q('Which unit is better for measuring the length of a classroom?','metres',['centimetres','metres','millimetres','cups'],'Use metres for longer objects or spaces.')}
case'area':a=rnd(2,8);b=rnd(2,6);return q(`A rectangle covers ${a} rows of ${b} equal squares. What is its area in square units?`,a*b,null,'Count all equal squares: rows × squares in each row.');
case'mass':a=rnd(2,10);b=rnd(1,a-1);return q(`A book balances with ${a} blocks and a toy with ${b} blocks. How many blocks heavier is the book?`,a-b,null,'Find the difference between the masses.');
case'capacity':a=rnd(3,10);b=rnd(1,a-1);return q(`Jug A holds ${a} cups. Jug B holds ${b} cups. How many more cups does Jug A hold?`,a-b,null,'Capacity tells how much a container can hold.');
case'shapes2d':{let items=[['triangle',3,3],['quadrilateral',4,4],['pentagon',5,5],['hexagon',6,6]],x=items[rnd(0,3)],mode=rnd(0,2);if(mode===0)return q(`How many sides does a ${x[0]} have?`,x[1],[3,4,5,6],'Count the straight sides.');if(mode===1)return q(`How many vertices does a ${x[0]} have?`,x[2],[3,4,5,6],'A vertex is a corner.');return q('Which shape must have exactly 4 straight sides?','quadrilateral',['triangle','quadrilateral','pentagon','hexagon'],'A quadrilateral is any polygon with 4 sides.')}
case'shapes3d':{let mode=rnd(0,2);if(mode===0)return q('Which 3D object has 6 square faces?','cube',['cube','sphere','cone','cylinder'],'A cube has 6 flat square faces.');if(mode===1)return q('Which 3D object has no flat faces?','sphere',['sphere','cube','rectangular prism','cylinder'],'A sphere has one curved surface and no flat face.');return q('Which 3D object has 2 flat circular faces and 1 curved surface?','cylinder',['cylinder','cone','sphere','cube'],'Think of the top and bottom of a can.')}
case'partition':{let den=[2,3,4][rnd(0,2)],name=den===2?'halves':den===3?'thirds':'quarters';return q(`A rectangle is divided into ${den} equal parts. What are the parts called?`,name,[name,'halves','thirds','quarters'],'Equal parts of a whole have special fraction names.')}
case'position':{let mode=rnd(0,1);if(mode===0)return q('You face north and make a quarter turn clockwise. Which direction are you facing?','East',['East','West','South','North'],'A clockwise quarter turn from north points east.');return q('You face east and make a half turn. Which direction are you facing?','West',['North','South','East','West'],'A half turn changes to the opposite direction.')}
case'data':{a=rnd(3,9);b=rnd(1,8);return q(`A tally table shows ${a} votes for apples and ${b} votes for bananas. How many votes altogether?`,a+b,null,'Add the frequencies in the table.')}
case'picturegraph':{let key=[1,2,5][rnd(0,2)],icons=rnd(2,6),ans=key*icons;return q(`In a picture graph, each ● represents ${key} children. One row has ${icons} ●. How many children does it represent?`,ans,null,'Multiply the number of pictures by the key value.')}
case'bargraph':{let cats={Cats:rnd(2,9),Dogs:rnd(2,9),Fish:rnd(2,9)},names=Object.keys(cats),mode=rnd(0,2);if(mode===0){let k=names[rnd(0,2)];return q(`A bar graph shows Cats ${cats.Cats}, Dogs ${cats.Dogs}, Fish ${cats.Fish}. How many chose ${k}?`,cats[k],[cats.Cats,cats.Dogs,cats.Fish,cats[k]+1],'Read the height/value of the correct bar.')}if(mode===1)return q(`A bar graph shows Cats ${cats.Cats}, Dogs ${cats.Dogs}, Fish ${cats.Fish}. How many responses altogether?`,cats.Cats+cats.Dogs+cats.Fish,null,'Add all category values.');let hi=names.reduce((x,y)=>cats[y]>cats[x]?y:x);return q(`Cats ${cats.Cats}, Dogs ${cats.Dogs}, Fish ${cats.Fish}. Which category has the most?`,hi,names,'The tallest bar represents the greatest value.')}
case'chance':return q('Which event is impossible?','Rolling a 7 on a normal six-sided die',['Rolling a 7 on a normal six-sided die','Rolling an even number','Getting heads on a coin','Picking one item from a bag'],'Impossible means it cannot happen.');}
return q('2 + 2 = ?',4,null,'Add the numbers.')}
function general(t){let c=cfg[grade],max=c.max,a,b;if(t==='mixed')t=base[rnd(0,4)][0];if(t==='addition'){a=rnd(0,max);b=rnd(0,max);return q(`${a} + ${b} = ?`,a+b,null,'Add by place value.')}if(t==='subtraction'){a=rnd(0,max);b=rnd(0,a);return q(`${a} − ${b} = ?`,a-b,null,'Subtract carefully.')}if(t==='multiplication'){a=rnd(1,grade==='K'?5:10);b=rnd(1,10);return q(`${a} × ${b} = ?`,a*b,null,'Think of equal groups.')}if(t==='division'){b=rnd(1,10);a=rnd(1,10);return q(`${a*b} ÷ ${b} = ?`,a,null,'Check by multiplying.')}a=rnd(0,max);b=rnd(0,max);return q(`Which number is greater: ${a} or ${b}?`,Math.max(a,b),[a,b],'Compare place values from left to right.')}
function setSize(){return grade==='2'?20:10}function buildTopics(){let list=grade==='2'?y2:base,host=$('topicGrid');host.innerHTML='';$('topicHeading').textContent=grade==='2'?'Year 2 Maths — full skill library':'What would you like to practise?';$('topicIntro').textContent=grade==='2'?`${y2.length-1} Year 2 skill areas with ${setSize()} original questions per set. Choose any area and generate unlimited new sets.`:'Each set contains questions matched to the selected year level.';list.forEach((x,i)=>{let b=document.createElement('button');b.className='p-topic '+(i===0?'active':'');b.dataset.topic=x[0];b.innerHTML=`<b>${x[1]}</b><strong>${x[2]}</strong><span>${x[3]}</span>`;b.onclick=()=>{host.querySelectorAll('button').forEach(z=>z.classList.remove('active'));b.classList.add('active');topic=x[0];buildSet();$('quiz').scrollIntoView({behavior:'smooth'})};host.appendChild(b)});topic=list[0][0]}
function topicName(){let list=grade==='2'?y2:base,x=list.find(x=>x[0]===topic);return x?x[2]:topic}function buildSet(){questions=Array.from({length:setSize()},()=>grade==='2'?y2q(topic):general(topic));idx=score=attempted=0;completed.clear();render()}function render(){let z=questions[idx];$('yearTag').textContent=`${cfg[grade].label.toUpperCase()} MATHS`;$('welcomeText').textContent=grade==='2'?`Hi ${profile.studentName||'there'}! Explore the expanded Year 2 skill library and generate as many practice sets as you need.`:`Hi ${profile.studentName||'there'}! Choose a skill and complete a short ${cfg[grade].label} practice set.`;$('topicBadge').textContent=topicName();$('quizTitle').textContent=`${topicName()} Practice`;$('qCount').textContent=`${idx+1} / ${questions.length}`;$('qBar').style.width=`${((idx+1)/questions.length)*100}%`;$('questionText').textContent=z.text;$('tipText').textContent=z.tip;$('scoreText').textContent=`${score} / ${attempted}`;$('practiceFeedback').textContent='';selected=null;let h=$('answerChoices');h.innerHTML='';z.choices.forEach((v,i)=>{let b=document.createElement('button');b.textContent=v;b.onclick=()=>{h.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=i};h.appendChild(b)});nav()}
function nav(){let h=$('questionNav');h.innerHTML='';questions.forEach((_,i)=>{let b=document.createElement('button');b.textContent=i+1;if(i===idx)b.classList.add('current');if(completed.has(i))b.classList.add('done');b.onclick=()=>{idx=i;render()};h.appendChild(b)})}
$('checkAnswer').onclick=()=>{if(selected===null){$('practiceFeedback').textContent='Choose an answer first.';return}if(completed.has(idx))return;let z=questions[idx],correctIndex=z.choices.findIndex(v=>String(v)===String(z.answer)),ok=selected===correctIndex;attempted++;if(ok)score++;document.querySelectorAll('#answerChoices button').forEach((b,i)=>{if(i===correctIndex)b.classList.add('correct');else if(i===selected)b.classList.add('wrong')});$('practiceFeedback').textContent=ok?'✓ Correct! Great work.':`Not quite. The correct answer is ${z.choices[correctIndex]}.`;$('practiceFeedback').style.color=ok?'#277c48':'#ad4949';completed.add(idx);$('scoreText').textContent=`${score} / ${attempted}`;nav();save()};$('nextQuestion').onclick=()=>{idx=(idx+1)%questions.length;render()};$('restartBtn').onclick=buildSet;$('gradeSelect').value=grade;$('studentChip').textContent=profile.studentName||'Student';$('gradeSelect').onchange=e=>{grade=e.target.value;profile.grade=grade;localStorage.setItem('tyProfile',JSON.stringify(profile));buildTopics();buildSet()};function save(){let all=JSON.parse(localStorage.getItem('tyPracticeProgress')||'{}');all[`${grade}-${topic}`]={score,attempted,date:new Date().toISOString()};localStorage.setItem('tyPracticeProgress',JSON.stringify(all))}buildTopics();buildSet();