/* SkillUP Science question bank: Kindy–Year 6. Each year has 20 original, age-appropriate questions. */
(function(){
  const q=(topic,text,answer,options,explanation)=>({topic,text,answer,options,explanation});
  const B={
"K":[
q("Living things","Which one is a living thing?","A tree",["A tree","A spoon","A ball","A shoe"],"A tree grows and needs water and light."),
q("Living things","What do most plants need to grow?","Water and light",["Water and light","Plastic and batteries","A television","Ice cream"],"Plants need water and light to grow."),
q("Living things","Which animal can move by flying?","A bird",["A bird","A fish","A worm","A snail"],"Birds use wings to fly."),
q("Weather","Which weather would you expect when you need an umbrella?","Rain",["Rain","Bright sunshine","Dry wind","Snow on the ground"],"An umbrella helps keep you dry in rain."),
q("Weather","What can you see in the sky on a clear day?","The Sun",["The Sun","A fish","Grass","A spoon"],"The Sun is in the sky and gives us light."),
q("Materials","Which object is usually made of glass?","A window",["A window","A jumper","A pencil","A wooden chair"],"Many windows are made from clear glass."),
q("Materials","Which material feels soft?","Cotton",["Cotton","Metal","Stone","Glass"],"Cotton is a soft material used for clothes."),
q("Materials","Which material is good for a raincoat because it keeps water out?","Waterproof plastic",["Waterproof plastic","Paper","Tissue","Dry sand"],"Waterproof plastic helps keep rain out."),
q("Movement","A push can make a toy car…","Move away from you",["Move away from you","Turn into water","Grow leaves","Become heavier"],"A push moves an object away."),
q("Movement","Which action is a pull?","Opening a drawer",["Opening a drawer","Kicking a ball","Blowing a bubble","Dropping a pencil"],"You pull a drawer towards you."),
q("Movement","What happens when a ball rolls down a ramp?","It moves",["It moves","It grows","It melts","It changes colour"],"A ramp can help an object move."),
q("Earth & sky","What do we see at night that can look round?","The Moon",["The Moon","A rainbow only","A tree","A chair"],"The Moon can be seen in the night sky."),
q("Earth & sky","The Sun gives Earth…","Light and warmth",["Light and warmth","Snow and ice","Sound only","Soil"],"The Sun provides light and heat."),
q("Earth & sky","Where do we live?","On Earth",["On Earth","On the Moon","Inside a cloud","On the Sun"],"Earth is our planet."),
q("Investigating","Which sense helps you hear a bell?","Hearing",["Hearing","Smell","Taste","Touch"],"Ears help us hear sounds."),
q("Investigating","Which sense helps you smell a flower?","Smell",["Smell","Sight","Hearing","Balance"],"Our nose helps us smell."),
q("Investigating","What should you do first when you notice something interesting?","Ask a question",["Ask a question","Hide it","Guess without looking","Break it"],"Scientists begin by asking questions."),
q("Investigating","Which tool can help you look closely at a small object?","A magnifying glass",["A magnifying glass","A pillow","A lunchbox","A shoe"],"A magnifying glass makes small details easier to see."),
q("Weather","Which clothing is useful on a cold day?","A warm coat",["A warm coat","Swim shorts","Sunglasses only","Sandals only"],"A warm coat helps keep your body warm."),
q("Living things","Which one is not living?","A rock",["A rock","A kitten","A flower","A tree"],"A rock does not grow or need food.")
],
"1":[
q("Living things","What do animals need to stay alive?","Food, water and air",["Food, water and air","Toys and paint","Only sunlight","A computer"],"Animals need food, water and air."),
q("Living things","Which part of a plant takes in water from the soil?","Roots",["Roots","Flowers","Fruit","Leaves only"],"Roots absorb water from the soil."),
q("Living things","Which animal begins life as an egg?","A chicken",["A chicken","A puppy","A kitten","A cow"],"Chickens hatch from eggs."),
q("Our bodies & senses","Which body part helps you see?","Eyes",["Eyes","Ears","Elbows","Toes"],"Eyes detect light and help us see."),
q("Our bodies & senses","Which body part helps you hear?","Ears",["Ears","Nose","Knees","Fingers"],"Ears detect sounds."),
q("Our bodies & senses","Which sense tells you that lemon is sour?","Taste",["Taste","Sight","Hearing","Touch"],"Your tongue helps you taste."),
q("Weather & seasons","Which season is usually the coldest in Australia?","Winter",["Winter","Summer","Autumn","Spring"],"Winter is generally the coldest season."),
q("Weather & seasons","What does a thermometer measure?","Temperature",["Temperature","Length","Mass","Sound"],"A thermometer measures how hot or cold something is."),
q("Weather & seasons","Which weather symbol usually shows rain?","A cloud with drops",["A cloud with drops","A bright sun only","A snowman only","A shoe"],"Raindrops under a cloud represent rain."),
q("Materials","Which material is transparent?","Clear glass",["Clear glass","Wood","Cardboard","Brick"],"Transparent materials let light through."),
q("Materials","Which material is flexible?","Rubber",["Rubber","Stone","Glass","Brick"],"Rubber can bend and stretch."),
q("Materials","Why is metal used for a saucepan?","It is strong and conducts heat",["It is strong and conducts heat","It can grow","It is soft like cotton","It is invisible"],"Metal is strong and transfers heat well."),
q("Earth & sky","Which object is a star?","The Sun",["The Sun","Earth","The Moon","A cloud"],"The Sun is the star closest to Earth."),
q("Earth & sky","What causes day and night?","Earth turning",["Earth turning","The Moon melting","Clouds moving","Trees growing"],"Earth rotates, giving us day and night."),
q("Earth & sky","The Moon is a…","Natural satellite of Earth",["Natural satellite of Earth","Star bigger than the Sun","Type of cloud","Country"],"The Moon orbits Earth."),
q("Forces & movement","A push or a pull is a…","Force",["Force","Colour","Sound","Material"],"A force is a push or a pull."),
q("Forces & movement","Which surface makes a toy car slow down most?","A rough carpet",["A rough carpet","Smooth ice","A polished table","A glass slide"],"Rough surfaces create more friction."),
q("Forces & movement","What force pulls objects towards Earth?","Gravity",["Gravity","Light","Magnetism only","Sound"],"Gravity pulls objects towards Earth."),
q("Investigating","What should you do to make a fair comparison?","Change one thing at a time",["Change one thing at a time","Change everything","Do not measure","Guess the result"],"Changing one variable makes a comparison fair."),
q("Investigating","Which tool measures length?","A ruler",["A ruler","A thermometer","A balance","A stopwatch"],"A ruler measures length.")
],
"2":[
q("Life cycles","Which stage comes after a seed begins to grow?","A seedling",["A seedling","A rock","A cloud","A fossil"],"A germinating seed becomes a seedling."),
q("Life cycles","A butterfly begins life as a…","Caterpillar",["Caterpillar","Puppy","Tadpole","Seed"],"A caterpillar is a young butterfly."),
q("Life cycles","What do baby animals usually need from adults?","Food and protection",["Food and protection","A battery","A ruler","Paint"],"Adult animals help babies survive."),
q("Habitats","A habitat is…","A place where an organism lives",["A place where an organism lives","A type of weather","A measuring tool","A star"],"A habitat provides an organism's needs."),
q("Habitats","Which habitat is best for a fish?","A pond",["A pond","A dry desert with no water","A cupboard","A road"],"Fish need water to live."),
q("Habitats","What is one way a cactus survives in a dry habitat?","It stores water",["It stores water","It grows gills","It makes snow","It needs no sunlight"],"Cacti store water in their thick stems."),
q("Materials","Which change is reversible?","Ice melting",["Ice melting","Paper burning","An egg cooking","Wood rotting"],"Melted water can freeze again."),
q("Materials","Which material is absorbent?","A sponge",["A sponge","A glass tile","A metal spoon","A plastic lid"],"A sponge soaks up liquid."),
q("Materials","Why are windows made from clear materials?","So light can pass through",["So light can pass through","So they can grow","So they absorb all water","So they are heavier"],"Clear materials let light through."),
q("Forces","Which force can attract some metal objects without touching them?","Magnetism",["Magnetism","Sound","Heat","Rain"],"Magnets attract some metals at a distance."),
q("Forces","A ramp makes it easier to move a heavy object because it…","Changes the direction and size of the force needed",["Changes the direction and size of the force needed","Makes it weightless","Stops gravity","Adds water"],"A ramp is an inclined plane that reduces effort."),
q("Forces","What can a force change?","An object's speed or direction",["An object's speed or direction","Its birthday","Its name","Its smell only"],"Forces can change motion."),
q("Earth & weather","What is water changing from liquid to vapour called?","Evaporation",["Evaporation","Freezing","Melting","Falling"],"Heat can change liquid water into vapour."),
q("Earth & weather","Clouds form when water vapour…","Cools and condenses",["Cools and condenses","Turns into metal","Gets louder","Becomes soil"],"Cooling water vapour forms tiny droplets."),
q("Earth & weather","Which instrument measures rainfall?","Rain gauge",["Rain gauge","Compass","Ruler","Balance"],"A rain gauge collects and measures rain."),
q("Investigations","A prediction is…","An idea about what may happen",["An idea about what may happen","A final measurement","A type of material","A weather instrument"],"A prediction is made before testing."),
q("Investigations","Why record results in a table?","To organise observations",["To organise observations","To make objects grow","To hide mistakes","To change the weather"],"Tables make results clear and easy to compare."),
q("Investigations","Which result is most useful?","A measurement with a unit",["A measurement with a unit","A guess with no evidence","A drawing only","A secret"],"Units tell us what a number means."),
q("Habitats","Which living thing helps pollinate many flowers?","A bee",["A bee","A rock","A pencil","A cloud"],"Bees carry pollen between flowers."),
q("Life cycles","What do plants make from flowers after pollination?","Seeds",["Seeds","Plastic","Rocks","Metal"],"Seeds allow new plants to grow.")
],
"3":[
q("Living world","What is a group of the same kind of organism called?","A species",["A species","A weather front","A mineral","A force"],"A species is a group that can reproduce similar young."),
q("Living world","Which feature helps a camel survive in a hot, dry habitat?","It can go a long time without water",["It can go a long time without water","It has gills","It needs snow","It cannot store fat"],"Camel adaptations help it survive dry conditions."),
q("Living world","In a food chain, plants are usually…","Producers",["Producers","Decomposers only","Top predators","Non-living"],"Plants make their own food using sunlight."),
q("Living world","What do decomposers do?","Break down dead material",["Break down dead material","Make sunlight","Stop all growth","Create gravity"],"Decomposers recycle nutrients."),
q("Material world","Which state of matter keeps its own shape?","Solid",["Solid","Liquid","Gas","Plasma"],"Solids have a fixed shape."),
q("Material world","What happens when water is heated to boiling?","It changes to a gas",["It changes to a gas","It becomes a solid","It disappears forever","It becomes metal"],"Boiling changes liquid water into water vapour."),
q("Material world","Which property describes how easily a material bends?","Flexibility",["Flexibility","Transparency","Mass","Temperature"],"Flexible materials bend without breaking."),
q("Material world","A mixture can usually be…","Separated using physical methods",["Separated using physical methods","Changed into a star","Made alive","Stopped from moving"],"Filtering or sorting can separate mixtures."),
q("Physical world","Which force slows a moving bicycle when brakes are used?","Friction",["Friction","Buoyancy","Light","Magnetism only"],"Brake pads create friction."),
q("Physical world","Sound is made by…","Vibrations",["Vibrations","Still objects","Darkness","Gravity alone"],"Vibrating objects produce sound."),
q("Physical world","Light travels from a lamp in…","Straight lines",["Straight lines","Squares","Spirals only","No direction"],"Light travels in straight lines."),
q("Physical world","Which object is attracted to a magnet?","An iron nail",["An iron nail","A wooden ruler","A plastic cup","A glass marble"],"Iron is magnetic."),
q("Earth & space","Earth takes about how long to rotate once?","24 hours",["24 hours","7 days","1 hour","365 years"],"One rotation of Earth makes one day."),
q("Earth & space","Earth takes about how long to orbit the Sun?","365 days",["365 days","24 hours","30 minutes","10 years"],"One orbit is about one year."),
q("Earth & space","A fossil is evidence of…","Past life",["Past life","Future weather","A new planet","Electric current"],"Fossils preserve traces of ancient organisms."),
q("Patterns in nature","Which is a repeating natural cycle?","Day and night",["Day and night","A single pencil","A broken cup","A one-off sound"],"Day and night repeat as Earth rotates."),
q("Investigations","The variable you deliberately change is the…","Independent variable",["Independent variable","Result only","Conclusion","Unit"],"The independent variable is what you change."),
q("Investigations","Why repeat a measurement?","To improve reliability",["To improve reliability","To remove all data","To change the question","To stop observation"],"Repeated results help identify a reliable pattern."),
q("Investigations","A conclusion should be based on…","Evidence from the results",["Evidence from the results","A random guess","The title only","A picture with no data"],"Conclusions explain what the evidence shows."),
q("Living world","Which relationship benefits both a bee and a flowering plant?","Pollination",["Pollination","Rusting","Evaporation","Reflection"],"Bees get nectar and plants are pollinated.")
],
"4":[
q("Living systems","An adaptation is a feature that helps an organism…","Survive in its environment",["Survive in its environment","Change into a rock","Stop needing energy","Make its own weather"],"Adaptations improve survival."),
q("Living systems","Which is an example of a food web role?","Predator",["Predator","Thermometer","Solvent","Circuit"],"A predator eats other organisms."),
q("Living systems","What do plants use to make food?","Light energy",["Light energy","Sound energy","Plastic","Sand only"],"Photosynthesis uses light energy."),
q("Living systems","Why are decomposers important in ecosystems?","They return nutrients to the soil",["They return nutrients to the soil","They remove all oxygen","They stop plants growing","They create sunlight"],"Decomposers recycle nutrients."),
q("Materials & change","Which change is reversible?","Salt dissolving in water",["Salt dissolving in water","Wood burning","An egg frying","Iron rusting"],"The salt can be recovered by evaporating the water."),
q("Materials & change","Which change forms a new substance?","Rusting iron",["Rusting iron","Cutting paper","Melting ice","Bending wire"],"Rust is a new substance formed from iron and oxygen."),
q("Materials & change","A solution is a mixture where one substance…","Dissolves in another",["Dissolves in another","Grows roots","Becomes a magnet","Turns into light"],"A solute dissolves in a solvent."),
q("Materials & change","Which method separates sand from water?","Filtering",["Filtering","Freezing the sand","Magnetising water","Shaking forever"],"A filter traps sand while water passes through."),
q("Forces & energy","Gravity is a force that…","Pulls masses together",["Pulls masses together","Pushes only sideways","Creates colour","Stops all motion"],"Gravity attracts objects with mass."),
q("Forces & energy","Which form of energy is stored in a stretched rubber band?","Elastic potential energy",["Elastic potential energy","Sound only","Light only","Nuclear energy"],"Stretching stores elastic energy."),
q("Forces & energy","A simple circuit needs a complete path for…","Electric current",["Electric current","Rainfall","Gravity only","Smell"],"Current flows around a complete circuit."),
q("Forces & energy","Which material is a good electrical conductor?","Copper",["Copper","Rubber","Dry wood","Plastic"],"Copper allows current to flow easily."),
q("Earth systems","The water cycle includes evaporation, condensation and…","Precipitation",["Precipitation","Combustion","Digestion","Magnetism"],"Precipitation is water falling as rain, snow or hail."),
q("Earth systems","What can weathering do to rocks?","Break them into smaller pieces",["Break them into smaller pieces","Make them alive","Turn them into clouds instantly","Remove gravity"],"Weathering breaks rocks down."),
q("Earth systems","Which layer of Earth do we live on?","The crust",["The crust","The inner core","The mantle only","The outer atmosphere"],"The crust is Earth's solid outer layer."),
q("Sustainability","Renewable energy comes from sources that…","Are naturally replaced",["Are naturally replaced","Run out after one use","Are always made of plastic","Cannot produce power"],"Sunlight and wind are renewable."),
q("Sustainability","Why should we reduce food waste?","To conserve resources",["To conserve resources","To increase rubbish","To use more water","To stop plants growing"],"Food uses land, water and energy."),
q("Investigations","A fair test keeps which things the same?","Controlled variables",["Controlled variables","The conclusion only","The question only","The final answer"],"Controlled variables are kept the same."),
q("Investigations","Which graph is useful for comparing categories?","A column graph",["A column graph","A weather forecast only","A map only","A sentence"],"Columns make category sizes easy to compare."),
q("Living systems","If one species disappears from a food web, what may happen?","Other populations can change",["Other populations can change","Nothing can ever change","Gravity stops","All plants become animals"],"Food webs show connected populations.")
],
"5":[
q("Living world","A trait that helps an organism survive is called an…","Adaptation",["Adaptation","Equation","Mixture","Orbit"],"Adaptations improve survival in a habitat."),
q("Living world","Which organism is a decomposer?","A fungus",["A fungus","A hawk","A gum tree","A kangaroo"],"Fungi break down dead material."),
q("Living world","In a food chain, arrows usually show the direction of…","Energy transfer",["Energy transfer","Animal movement only","Rainfall","Time"],"Energy moves from food to the eater."),
q("Living world","Why are producers important?","They introduce energy into food webs",["They introduce energy into food webs","They eat all predators","They create rocks","They stop decomposition"],"Plants capture light energy."),
q("Material world","Which is a physical change?","Crushing a can",["Crushing a can","Burning paper","Rusting iron","Cooking an egg"],"Crushing changes shape but not the substance."),
q("Material world","Which is a chemical change?","Burning wood",["Burning wood","Freezing water","Cutting cloth","Dissolving sugar"],"Burning creates new substances such as ash and gases."),
q("Material world","What is the best way to separate iron filings from sand?","A magnet",["A magnet","A sieve with water","A thermometer","A ruler"],"Iron is attracted to magnets."),
q("Material world","In salt water, the salt is the…","Solute",["Solute","Solvent","Precipitate only","Gas"],"The solute dissolves in the solvent."),
q("Physical world","A torch changes stored chemical energy in its battery mainly into…","Light energy",["Light energy","Mass","Soil","Gravity"],"The battery supplies energy for the lamp."),
q("Physical world","Which circuit component provides electrical energy?","A battery",["A battery","A switch only","A wire only","A bulb cover"],"A battery provides a potential difference."),
q("Physical world","What happens to current in a series circuit if the circuit is open?","It stops flowing",["It stops flowing","It doubles","It becomes water","It travels through air"],"An open circuit has a break."),
q("Physical world","Which force opposes motion between surfaces?","Friction",["Friction","Gravity only","Light","Sound"],"Friction acts against sliding."),
q("Earth & space","Which object orbits a planet?","A moon",["A moon","A cloud","A mountain","A continent"],"Moons orbit planets."),
q("Earth & space","Why do we have seasons?","Earth's tilted axis as it orbits the Sun",["Earth's tilted axis as it orbits the Sun","The Moon changing colour","Clouds stopping sunlight","Earth moving closer every day"],"Tilt changes the angle and length of sunlight."),
q("Earth & space","What is the path of a planet around a star called?","An orbit",["An orbit","A habitat","A circuit","A cycle of matter"],"Planets travel in orbits."),
q("Sustainability","Which action best conserves water?","Fixing a leaking tap",["Fixing a leaking tap","Leaving water running","Washing one item many times","Pouring clean water away"],"Fixing leaks prevents waste."),
q("Sustainability","A species is endangered when it…","Faces a high risk of extinction",["Faces a high risk of extinction","Is common everywhere","Has no habitat needs","Can never reproduce"],"Endangered species need protection."),
q("Scientific inquiry","A hypothesis is…","A testable explanation",["A testable explanation","A measurement unit","A final mark","A type of force"],"A hypothesis can be tested with evidence."),
q("Scientific inquiry","Why should results include units?","So measurements have meaning",["So measurements have meaning","To make numbers larger","To hide variation","To change the variable"],"Centimetres, seconds and grams describe the measurement."),
q("Scientific inquiry","Which conclusion is strongest?","One supported by repeated results",["One supported by repeated results","One based on a guess","One with no measurements","One copied before testing"],"Repeated evidence makes a conclusion more trustworthy.")
],
"6":[
q("Living systems","What is biodiversity?","The variety of living things",["The variety of living things","The speed of light","A type of rock","A measurement unit"],"Biodiversity describes the variety of organisms."),
q("Living systems","Which change can reduce biodiversity?","Habitat destruction",["Habitat destruction","Protecting wetlands","Planting native trees","Creating wildlife corridors"],"Loss of habitat can remove species."),
q("Living systems","Why are food webs more realistic than simple food chains?","They show many connected feeding relationships",["They show many connected feeding relationships","They only show plants","They remove decomposers","They show weather only"],"Most organisms have more than one food relationship."),
q("Living systems","Natural selection can cause populations to…","Change over many generations",["Change over many generations","Change instantly when named","Stop needing energy","Become non-living"],"Helpful inherited traits can become more common."),
q("Materials","Which evidence suggests a chemical reaction?","A gas forms and a new colour appears",["A gas forms and a new colour appears","A block is cut","Ice melts","Water is poured"],"Gas and colour change can indicate a new substance."),
q("Materials","Which process is reversible?","Filtering muddy water",["Filtering muddy water","Burning fuel","Baking bread","Rusting a nail"],"Filtering separates substances without forming a new one."),
q("Materials","Why does increasing temperature often speed up dissolving?","Particles move faster",["Particles move faster","The solute becomes alive","Gravity disappears","The solvent becomes solid"],"Faster-moving particles mix more quickly."),
q("Materials","What does pH help describe?","How acidic or alkaline a solution is",["How acidic or alkaline a solution is","How long a wire is","How heavy a rock is","How bright a star is"],"pH is a measure of acidity and alkalinity."),
q("Energy & forces","Energy cannot be created or destroyed, but it can be…","Transferred or transformed",["Transferred or transformed","Made from nothing","Removed from the universe","Changed into mass only"],"Energy moves between stores and forms."),
q("Energy & forces","In a parallel circuit, one lamp can stay on if another lamp…","Is removed from its branch",["Is removed from its branch","Is painted","Loses its colour","Is placed beside a battery"],"Separate branches can continue to carry current."),
q("Energy & forces","Acceleration means a change in…","Velocity",["Velocity","Mass only","Colour","Temperature only"],"Acceleration is a change in speed or direction."),
q("Energy & forces","Which variable affects the gravitational force between objects?","Mass",["Mass","Colour","Sound","Shape of a letter"],"More mass means stronger gravitational attraction."),
q("Earth & space","What causes the apparent movement of the Sun across the sky?","Earth's rotation",["Earth's rotation","The Sun orbiting Earth each day","Clouds pulling the Sun","The Moon switching it off"],"Earth rotates from west to east."),
q("Earth & space","A lunar eclipse occurs when…","Earth is between the Sun and Moon",["Earth is between the Sun and Moon","The Moon is between Earth and the Sun every day","The Sun is behind a cloud","Earth stops rotating"],"Earth's shadow falls on the Moon."),
q("Earth & space","Which Earth system includes oceans, rivers and ice?","Hydrosphere",["Hydrosphere","Biosphere","Lithosphere","Atmosphere only"],"The hydrosphere is all Earth's water."),
q("Science & society","Why do scientists publish methods and results?","So others can evaluate and repeat the work",["So others can evaluate and repeat the work","To hide evidence","To avoid measurement","To make results private"],"Open methods support checking and replication."),
q("Science & society","Which is an example of a sustainable choice?","Using renewable energy and reducing waste",["Using renewable energy and reducing waste","Using more single-use plastic","Wasting clean water","Removing native habitats"],"Sustainability protects resources for the future."),
q("Scientific inquiry","A controlled variable is a factor that is…","Kept the same during a fair test",["Kept the same during a fair test","Changed on every trial","The final conclusion","Never measured"],"Controls make comparisons fair."),
q("Scientific inquiry","Why repeat trials?","To identify patterns and reduce random error",["To identify patterns and reduce random error","To guarantee the preferred result","To avoid recording data","To change the hypothesis after every trial"],"Repeats improve confidence in results."),
q("Scientific inquiry","Which statement is a conclusion rather than an observation?","The plant grew faster in brighter light",["The plant grew faster in brighter light","The plant was 12 cm tall","The lamp was on","There were four leaves"],"A conclusion interprets observations and measurements.")
]
};
  window.SKILLUP_SCIENCE=B;
})();