// Grade 4 topics follow the 14 chapters of Progress in Mathematics Grade 4.
// Questions are newly written for SkillUP and do not reproduce the textbook.
(function () {
  const R=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
  const P=a=>a[R(0,a.length-1)];
  const S=a=>[...a].sort(()=>Math.random()-.5);
  const gcd=(a,b)=>b?gcd(b,a%b):Math.abs(a);
  const frac=(n,d)=>{const g=gcd(n,d);return `${n/g}/${d/g}`};
  const cash=n=>`$${Number(n).toFixed(2)}`;
  const topics=[
    ['placevalue','123','1. Place Value','Thousands to millions, number lines, money, estimation, comparison and rounding'],
    ['addsubconcepts','+−','2. Addition & Subtraction Concepts','Properties, mental strategies, variables, number sentences, estimation and money'],
    ['addition','+−','3. Addition & Subtraction','Regrouping, large numbers, several addends, zeros and operation choice'],
    ['multiplication','×','4. Multiply by One and Two Digits','Properties, models, estimation, patterns, money and multi-digit products'],
    ['division','÷','5. Divide by One Digit','Rules, patterns, estimation, divisibility, remainders, mean and operation order'],
    ['measurement','cm','6. Measurement','Customary and metric units, capacity, mass, temperature, time and elapsed time'],
    ['data','▥','7. Statistics & Probability','Graphs, surveys, combinations, outcomes and probability'],
    ['fractionconcepts','½','8. Fraction Concepts','Number lines, estimation, equivalent fractions, lowest terms, mixed numbers and ordering'],
    ['fractionoperations','¾','9. Fractions: Addition & Subtraction','Like and unlike denominators, mixed numbers, probability and fractions of quantities'],
    ['geometry','∠','10. Geometry','Lines, angles, circles, polygons, triangles, transformations and coordinates'],
    ['perimeterarea','▭','11. Perimeter, Area & Volume','Formulas, solid figures, spatial relationships and volume'],
    ['division2digit','÷÷','12. Divide by Two Digits','Division patterns, estimation, trial quotients, large dividends and zeros'],
    ['decimals','.01','13. Decimals','Place value, comparison, ordering, rounding, estimation and decimal operations'],
    ['equations','x','14. Equations & Functions','Missing numbers, functions, graphing, symbols and parentheses'],
    ['mixed','⚡','Mixed Grade 4 Challenge','Questions selected from all 14 Grade 4 chapters']
  ];
  function nums(ans,step=1,min=-Infinity){const v=new Set([Number(ans)]);let k=1;while(v.size<4){v.add(Math.max(min,Number(ans)+k*step));if(v.size<4)v.add(Math.max(min,Number(ans)-k*step));k++}return S([...v].map(String))}
  function Q(text,answer,choices,tip,explanation){const a=String(answer),c=[...new Set(choices.map(String))];if(!c.includes(a))c.unshift(a);return{text,answer:a,choices:S(c.slice(0,4)),tip,explanation:explanation||`${tip} The answer is ${a}.`}}
  function place(){const m=R(0,4);if(m===0){const d=R(2,9),n=d*100000+R(1000,99999);return Q(`What is the value of ${d} in ${n.toLocaleString()}?`,(d*100000).toLocaleString(),[(d*100000).toLocaleString(),(d*10000).toLocaleString(),d,(d*1000).toLocaleString()],'Identify the digit’s place.',`${d} is in the hundred-thousands place.`)}if(m===1){const n=R(10000,999999),a=Math.round(n/1000)*1000;return Q(`Round ${n.toLocaleString()} to the nearest thousand.`,a.toLocaleString(),[a.toLocaleString(),(Math.floor(n/1000)*1000).toLocaleString(),(Math.ceil(n/10000)*10000).toLocaleString(),n.toLocaleString()],'Look at the hundreds digit.',`${n.toLocaleString()} rounds to ${a.toLocaleString()}.`)}if(m===2){const a=R(10000,999999),b=R(10000,999999);return Q(`Which number is greater: ${a.toLocaleString()} or ${b.toLocaleString()}?`,Math.max(a,b).toLocaleString(),[a.toLocaleString(),b.toLocaleString()],'Compare from the greatest place value.',`${Math.max(a,b).toLocaleString()} is greater.`)}if(m===3){const s=R(10,60)*1000,k=R(2,9)*1000,a=s+3*k;return Q(`Complete the number line: ${s.toLocaleString()}, ${(s+k).toLocaleString()}, ${(s+2*k).toLocaleString()}, __.`,a.toLocaleString(),nums(a,k,0).map(Number).map(x=>x.toLocaleString()),'Find the equal interval.',`The interval is ${k.toLocaleString()}, so the next number is ${a.toLocaleString()}.`)}const paid=R(20,100),cost=R(5,paid-1)+P([0,.25,.5,.75]);return Q(`An item costs ${cash(cost)}. You pay $${paid}. What is the change?`,cash(paid-cost),[cash(paid-cost),cash(cost),cash(paid+cost),cash(Math.abs(paid-cost-1))],'Change equals amount paid minus cost.',`${cash(paid)} − ${cash(cost)} = ${cash(paid-cost)}.`)}
  function concepts(){const m=R(0,4);if(m===0)return Q('Which property is shown by 46 + 29 = 29 + 46?','Commutative property',['Commutative property','Associative property','Identity property','Distributive property'],'The order changes, but the sum does not.','This is the commutative property.');if(m===1){const x=R(20,90),b=R(10,50);return Q(`□ + ${b} = ${x+b}. What is □?`,x,nums(x,5,0),'Use subtraction to find the missing addend.',`${x+b} − ${b} = ${x}.`)}if(m===2){const n=R(5,30),b=R(3,15);return Q(`If n = ${n}, find n + ${b}.`,n+b,nums(n+b,2,0),'Substitute the value of n.',`${n} + ${b} = ${n+b}.`)}if(m===3){const a=R(120,980),b=R(120,980),ans=Math.round(a/100)*100+Math.round(b/100)*100;return Q(`Estimate ${a} + ${b} by rounding to hundreds.`,ans,nums(ans,100,0),'Round both addends, then add.',`${a} ≈ ${Math.round(a/100)*100} and ${b} ≈ ${Math.round(b/100)*100}; estimate ${ans}.`)}const a=R(10,80)+P([.25,.5,.75]),b=R(5,40)+P([.25,.5,.75]);return Q(`${cash(a)} + ${cash(b)} = ?`,cash(a+b),[cash(a+b),cash(Math.abs(a-b)),cash(a+b+1),cash(a)],'Align decimal points.',`${cash(a)} + ${cash(b)} = ${cash(a+b)}.`)}
  function addsub(){const m=R(0,4);if(m===0){const a=R(1000,99999),b=R(1000,99999);return Q(`${a.toLocaleString()} + ${b.toLocaleString()} = ?`,(a+b).toLocaleString(),nums(a+b,100,0).map(Number).map(x=>x.toLocaleString()),'Align place values and regroup.',`${a.toLocaleString()} + ${b.toLocaleString()} = ${(a+b).toLocaleString()}.`)}if(m===1){const a=R(5000,99999),b=R(1000,a-1);return Q(`${a.toLocaleString()} − ${b.toLocaleString()} = ?`,(a-b).toLocaleString(),nums(a-b,100,0).map(Number).map(x=>x.toLocaleString()),'Subtract by place value.',`${a.toLocaleString()} − ${b.toLocaleString()} = ${(a-b).toLocaleString()}.`)}if(m===2){const a=R(100,999),b=R(100,999),c=R(100,999);return Q(`${a} + ${b} + ${c} = ?`,a+b+c,nums(a+b+c,10,0),'Add all three addends.',`${a} + ${b} + ${c} = ${a+b+c}.`)}if(m===3){const a=R(3,8)*10000+R(1,9),b=R(100,9999);return Q(`${a.toLocaleString()} − ${b.toLocaleString()} = ?`,(a-b).toLocaleString(),nums(a-b,10,0).map(Number).map(x=>x.toLocaleString()),'Regroup across zeros one place at a time.',`The difference is ${(a-b).toLocaleString()}.`)}const total=R(2000,9000),part=R(500,total-500);return Q(`A library has ${total.toLocaleString()} books. ${part.toLocaleString()} are fiction. How many are not fiction?`,(total-part).toLocaleString(),nums(total-part,100,0).map(Number).map(x=>x.toLocaleString()),'Subtract the known part from the total.',`${total.toLocaleString()} − ${part.toLocaleString()} = ${(total-part).toLocaleString()}.`)}
  function multiply(){const m=R(0,5);if(m===0)return Q('Which property is shown by 7 × 1 = 7?','Identity property',['Identity property','Zero property','Commutative property','Associative property'],'Multiplying by 1 leaves the number unchanged.','This is the identity property.');if(m===1){const a=R(20,999),b=R(2,9);return Q(`${a} × ${b} = ?`,a*b,nums(a*b,b,0),'Partition the larger factor.',`${a} × ${b} = ${a*b}.`)}if(m===2){const a=R(20,999),b=R(12,49);return Q(`${a} × ${b} = ?`,a*b,nums(a*b,a,0),'Add the tens and ones partial products.',`${a} × ${b} = ${a*b}.`)}if(m===3){const p=R(3,20)+P([.25,.5,.75]),n=R(2,9);return Q(`${n} items cost ${cash(p)} each. What is the total?`,cash(p*n),[cash(p*n),cash(p+n),cash(p*(n+1)),cash(p)],'Multiply price by quantity.',`${n} × ${cash(p)} = ${cash(p*n)}.`)}if(m===4){const a=R(21,89),b=R(12,48),ra=Math.round(a/10)*10,rb=Math.round(b/10)*10;return Q(`Estimate ${a} × ${b} by rounding to tens.`,ra*rb,nums(ra*rb,100,0),'Round both factors, then multiply.',`${ra} × ${rb} = ${ra*rb}.`)}const k=R(2,9),s=R(2,8);return Q(`Complete the pattern: ${k*s}, ${k*(s+1)}, ${k*(s+2)}, __.`,k*(s+3),nums(k*(s+3),k,0),`Add ${k} each time.`,`${k*(s+2)} + ${k} = ${k*(s+3)}.`)}
  function divide(){const m=R(0,6);if(m===0){const d=R(2,9),q=R(12,99);return Q(`${d*q} ÷ ${d} = ?`,q,nums(q,2,0),'Use the related multiplication fact.',`${d} × ${q} = ${d*q}.`)}if(m===1){const d=R(2,9),q=R(20,90),r=R(1,d-1),n=d*q+r,a=`${q} remainder ${r}`;return Q(`${n} ÷ ${d} = ?`,a,[a,`${q+1} remainder 0`,`${q} remainder ${r-1}`,`${q-1} remainder ${r}`],'Make complete groups, then count leftovers.',`${d} × ${q} = ${d*q}, leaving ${r}.`)}if(m===2){const d=R(3,9),n=d*R(30,90)+R(0,d-1),near=Math.round(n/(d*10))*d*10;return Q(`Estimate ${n} ÷ ${d} using ${near}.`,near/d,nums(near/d,10,0),'Use a nearby compatible number.',`${near} ÷ ${d} = ${near/d}.`)}if(m===3){const n=P([126,234,315,432,540,648]),d=P([2,3,5,6,9]),a=n%d===0?'Yes':'No';return Q(`Is ${n} divisible by ${d}?`,a,['Yes','No'],'Use a divisibility rule.',`${n} ${a==='Yes'?'is':'is not'} divisible by ${d}.`)}if(m===4){const a=R(2,9),b=R(2,9),c=R(2,9);return Q(`${a*b} ÷ ${a} + ${c} = ?`,b+c,nums(b+c,1,0),'Do division before addition.',`${a*b} ÷ ${a} = ${b}; ${b} + ${c} = ${b+c}.`)}if(m===5){const mean=R(5,20),v=[mean-3,mean-1,mean+1,mean+3];return Q(`Find the mean of ${v.join(', ')}.`,mean,nums(mean,2,0),'Add and divide by 4.',`The total is ${mean*4}; ${mean*4} ÷ 4 = ${mean}.`)}const g=R(3,8),e=R(10,40);return Q(`□ ÷ ${g} = ${e}. What is □?`,g*e,nums(g*e,g,0),'Use multiplication.',`${g} × ${e} = ${g*e}.`)}
  function measure(){const m=R(0,6);if(m===0){const f=R(2,12);return Q(`${f} feet equals how many inches?`,`${f*12} inches`,[`${f*12} inches`,`${f+12} inches`,`${f*3} inches`,`${f*36} inches`],'1 foot = 12 inches.',`${f} × 12 = ${f*12} inches.`)}if(m===1){const g=R(2,8);return Q(`${g} gallons equals how many quarts?`,`${g*4} quarts`,[`${g*4} quarts`,`${g*2} quarts`,`${g*8} quarts`,`${g+4} quarts`],'1 gallon = 4 quarts.',`${g} × 4 = ${g*4} quarts.`)}if(m===2){const x=R(2,25);return Q(`${x} metres equals how many centimetres?`,`${x*100} cm`,[`${x*100} cm`,`${x*10} cm`,`${x*1000} cm`,`${x} cm`],'1 metre = 100 centimetres.',`${x} × 100 = ${x*100} cm.`)}if(m===3){const x=R(2,15);return Q(`${x} litres equals how many millilitres?`,`${x*1000} mL`,[`${x*1000} mL`,`${x*100} mL`,`${x*10} mL`,`${x} mL`],'1 litre = 1000 millilitres.',`${x} × 1000 = ${x*1000} mL.`)}if(m===4){const x=R(2,12);return Q(`${x} kilograms equals how many grams?`,`${x*1000} g`,[`${x*1000} g`,`${x*100} g`,`${x*10} g`,`${x} g`],'1 kilogram = 1000 grams.',`${x} × 1000 = ${x*1000} g.`)}if(m===5){const s=R(-5,10),r=R(3,12);return Q(`The temperature is ${s}°C and rises by ${r}°C. What is it now?`,`${s+r}°C`,[`${s+r}°C`,`${s-r}°C`,`${r-s}°C`,`${r}°C`],'Add the increase.',`${s} + ${r} = ${s+r}°C.`)}const h=R(1,5),min=P([10,15,20,30,45]);return Q(`${h} h ${min} min equals how many minutes?`,`${h*60+min} min`,[`${h*60+min} min`,`${h*100+min} min`,`${h*60} min`,`${h*60+min+60} min`],'Convert hours to minutes.',`${h} × 60 + ${min} = ${h*60+min} minutes.`)}
  function stats(){const m=R(0,5);if(m===0){const key=P([2,5,10]),n=R(3,8);return Q(`Each symbol in a pictograph means ${key} students. What do ${n} symbols mean?`,n*key,nums(n*key,key,0),'Multiply symbols by the key.',`${n} × ${key} = ${n*key}.`)}if(m===1){const a=R(8,25),b=R(8,25);return Q(`A bar graph shows ${a} votes and ${b} votes. How many altogether?`,a+b,nums(a+b,2,0),'Add the bar values.',`${a} + ${b} = ${a+b}.`)}if(m===2)return Q('Which survey question is unbiased?','Which sport do you prefer?',['Which sport do you prefer?','Isn’t football the best sport?','Why is tennis boring?','You agree swimming is easiest, don’t you?'],'A fair question is neutral.','“Which sport do you prefer?” is neutral.');if(m===3){const a=R(2,5),b=R(2,4);return Q(`${a} shirts can be paired with ${b} shorts. How many outfits?`,a*b,nums(a*b,1,0),'Multiply to count combinations.',`${a} × ${b} = ${a*b}.`)}if(m===4){const a=R(2,8),b=R(2,8),ans=frac(a,a+b);return Q(`A bag has ${a} red and ${b} blue counters. What is P(red)?`,ans,[ans,frac(b,a+b),`${a}/${b}`,`1/${a+b}`],'Favourable outcomes ÷ total outcomes.',`P(red) = ${a}/${a+b} = ${ans}.`)}const p=P([25,50,75]),a=p*3.6;return Q(`A circle graph sector is ${p}%. What is its angle?`,`${a}°`,[`${a}°`,`${p}°`,`${360-a}°`,`${p*2}°`],'Find the percentage of 360°.',`${p}% of 360° is ${a}°.`)}
  function fractionConcept(){const m=R(0,6);if(m===0){const d=P([3,4,5,6,8]),n=R(1,d-1);return Q(`${n} of ${d} equal parts are shaded. What fraction?`,`${n}/${d}`,[`${n}/${d}`,`${d}/${n}`,`1/${d}`,`${n}/${d+1}`],'Numerator is shaded parts; denominator is all parts.',`The fraction is ${n}/${d}.`)}if(m===1){const d=P([4,5,6,8,10]),n=R(1,d-1);return Q(`A 0–1 number line has ${d} equal parts. What fraction is at mark ${n}?`,`${n}/${d}`,[`${n}/${d}`,`1/${d}`,`${d}/${n}`,`${n+1}/${d}`],'Each step is one equal part.',`Mark ${n} is ${n}/${d}.`)}if(m===2)return Q('Which fraction is closest to 1?','7/8',['7/8','1/8','3/8','1/2'],'Look for the smallest missing part.','7/8 is only 1/8 below 1.');if(m===3){const n=R(1,4),d=R(n+1,7),k=R(2,5),a=`${n*k}/${d*k}`;return Q(`Which fraction equals ${n}/${d}?`,a,[a,`${n+k}/${d+k}`,`${n*k}/${d}`,`${n}/${d*k}`],'Multiply top and bottom by the same number.',`${n}/${d} = ${a}.`)}if(m===4){const n=P([6,8,9,10,12]),d=P([12,16,18,20,24]),a=frac(n,d);return Q(`Write ${n}/${d} in lowest terms.`,a,[a,`${n}/${d}`,`${n/2}/${d}`,`${n}/${d/2}`],'Divide by the greatest common factor.',`${n}/${d} simplifies to ${a}.`)}if(m===5){const w=R(1,5),d=P([3,4,5,6]),n=R(1,d-1),top=w*d+n;return Q(`Write ${top}/${d} as a mixed number.`,`${w} ${n}/${d}`,[`${w} ${n}/${d}`,`${w+1} ${n}/${d}`,`${w} ${d}/${n}`,`${top-d}/${d}`],'Divide numerator by denominator.',`${top} ÷ ${d} = ${w} remainder ${n}.`)}return Q('Which list is least to greatest?','1/4, 1/2, 3/4',['1/4, 1/2, 3/4','3/4, 1/2, 1/4','1/2, 1/4, 3/4','1/4, 3/4, 1/2'],'Compare using fourths.','1/4 < 2/4 < 3/4.')}
  function fractionOps(){const m=R(0,5);if(m===0){const d=P([5,6,8,10]),a=R(1,d-2),b=R(1,d-a),ans=frac(a+b,d);return Q(`${a}/${d} + ${b}/${d} = ?`,ans,[ans,`${a+b}/${d*2}`,frac(a*b,d),frac(Math.abs(a-b),d)],'Add numerators for like denominators.',`${a}/${d} + ${b}/${d} = ${ans}.`)}if(m===1){const d=P([5,6,8,10]),a=R(2,d-1),b=R(1,a-1),ans=frac(a-b,d);return Q(`${a}/${d} − ${b}/${d} = ?`,ans,[ans,`${a-b}/${d*2}`,frac(a+b,d),frac(a*b,d)],'Subtract numerators for like denominators.',`${a}/${d} − ${b}/${d} = ${ans}.`)}if(m===2){const a=P([[1,2],[1,3],[1,4],[2,3]]),b=P([[1,4],[1,5],[2,5],[3,8]]),ans=frac(a[0]*b[1]+b[0]*a[1],a[1]*b[1]);return Q(`${a[0]}/${a[1]} + ${b[0]}/${b[1]} = ?`,ans,[ans,frac(a[0]+b[0],a[1]+b[1]),frac(a[0]*b[0],a[1]*b[1]),frac(Math.abs(a[0]*b[1]-b[0]*a[1]),a[1]*b[1])],'Use a common denominator.',`The sum simplifies to ${ans}.`)}if(m===3){const a=P([3,4,5,6]),b=P([4,5,6,8]),ans=Math.abs(a*b)/gcd(a,b);return Q(`Find the least common multiple of ${a} and ${b}.`,ans,nums(ans,Math.min(a,b),1),'List multiples until the first match.',`The LCM is ${ans}.`)}if(m===4){const d=P([2,3,4,5,8]),w=d*R(3,12);return Q(`What is 1/${d} of ${w}?`,w/d,nums(w/d,1,0),'Divide by the denominator.',`${w} ÷ ${d} = ${w/d}.`)}const f=R(1,5),t=f+R(2,7),ans=frac(f,t);return Q(`${f} of ${t} outcomes are favourable. What is the probability?`,ans,[ans,frac(t-f,t),`${f}/${t-f}`,`1/${t}`],'Favourable outcomes ÷ total outcomes.',`The probability is ${ans}.`)}
  function geometry(){const m=R(0,7);if(m===0)return Q('Which figure extends forever in both directions?','line',['line','line segment','ray','angle'],'A line has arrows at both ends.','A line extends forever both ways.');if(m===1)return Q('Which angle is greater than 90° but less than 180°?','obtuse angle',['obtuse angle','acute angle','right angle','straight angle'],'Compare with 90° and 180°.','That is an obtuse angle.');if(m===2)return Q('Lines meeting at four right angles are…','perpendicular',['perpendicular','parallel','curved','similar'],'Perpendicular lines meet at 90°.','They are perpendicular.');if(m===3){const r=R(2,12);return Q(`A circle has radius ${r} cm. What is its diameter?`,`${2*r} cm`,[`${2*r} cm`,`${r} cm`,`${r*r} cm`,`${r+2} cm`],'Diameter = 2 × radius.',`2 × ${r} = ${2*r} cm.`)}if(m===4)return Q('Which polygon has five sides?','pentagon',['pentagon','hexagon','quadrilateral','triangle'],'Count the sides.','A pentagon has five sides.');if(m===5)return Q('Which transformation slides a figure without turning it?','translation',['translation','reflection','rotation','enlargement'],'A slide has another mathematical name.','A slide is a translation.');if(m===6){const x=R(1,9),y=R(1,9);return Q(`For point (${x}, ${y}), what is the y-coordinate?`,y,[y,x,x+y,Math.abs(x-y)],'Coordinates are (x, y).',`The y-coordinate is ${y}.`)}return Q('Which quadrilateral has four right angles?','rectangle',['rectangle','kite','trapezoid','rhombus'],'Check the angle properties.','A rectangle has four right angles.')}
  function perimeter(){const m=R(0,5);if(m===0){const l=R(4,20),w=R(3,15),a=2*(l+w);return Q(`Perimeter of a ${l} cm by ${w} cm rectangle?`,`${a} cm`,[`${a} cm`,`${l*w} cm`,`${l+w} cm`,`${a} cm²`],'P = 2(l + w).',`2(${l}+${w}) = ${a} cm.`)}if(m===1){const l=R(4,20),w=R(3,15),a=l*w;return Q(`Area of a ${l} cm by ${w} cm rectangle?`,`${a} cm²`,[`${a} cm²`,`${2*(l+w)} cm²`,`${l+w} cm²`,`${a} cm`],'Area = length × width.',`${l} × ${w} = ${a} cm².`)}if(m===2){const p=R(12,30)*2,l=R(5,p/2-2),w=p/2-l;return Q(`A rectangle has perimeter ${p} cm and length ${l} cm. Find its width.`,`${w} cm`,[`${w} cm`,`${p-l} cm`,`${p/2} cm`,`${l} cm`],'Half the perimeter equals length + width.',`${p}/2 − ${l} = ${w} cm.`)}if(m===3)return Q('How many faces does a rectangular prism have?',6,['6','4','8','12'],'Count the flat surfaces.','It has 6 faces.');if(m===4)return Q('Which solid has two circular faces and one curved surface?','cylinder',['cylinder','cube','cone','sphere'],'Think about flat and curved surfaces.','A cylinder has those surfaces.');const l=R(2,10),w=R(2,8),h=R(2,7),a=l*w*h;return Q(`Volume of a ${l} cm × ${w} cm × ${h} cm prism?`,`${a} cm³`,[`${a} cm³`,`${2*(l+w+h)} cm³`,`${l*w} cm³`,`${l+w+h} cm³`],'Volume = l × w × h.',`${l} × ${w} × ${h} = ${a} cm³.`)}
  function divideTwo(){const m=R(0,5);if(m===0){const q=R(2,9),n=q*120;return Q(`${n} ÷ 12 = ?`,q*10,nums(q*10,10,0),'Use place-value patterns.',`${n} ÷ 12 = ${q*10}.`)}if(m===1){const d=P([20,30,40,50]),q=R(2,20);return Q(`${d*q} ÷ ${d} = ?`,q,nums(q,2,0),'Use multiplication facts with tens.',`${d} × ${q} = ${d*q}.`)}if(m===2){const d=R(12,39),q=R(10,40),n=d*q+R(0,d-1),ed=Math.round(d/10)*10,en=Math.round(n/100)*100,e=Math.round(en/ed);return Q(`Estimate ${n} ÷ ${d} using ${en} ÷ ${ed}.`,e,nums(e,2,0),'Use rounded compatible numbers.',`${en} ÷ ${ed} ≈ ${e}.`)}if(m===3){const d=R(11,49),q=R(2,90);return Q(`${d*q} ÷ ${d} = ?`,q,nums(q,5,0),'Use multiplication to check.',`${d} × ${q} = ${d*q}.`)}if(m===4){const d=P([12,15,20,25]),q=P([10,20,30,40]);return Q(`${d*q} ÷ ${d} = ?`,q,nums(q,10,0),'Keep place value, including zero.',`${d} × ${q} = ${d*q}.`)}const d=R(12,39),q=R(10,60),r=R(1,d-1),n=d*q+r,a=`${q} remainder ${r}`;return Q(`${n} ÷ ${d} = ?`,a,[a,`${q+1} remainder 0`,`${q} remainder ${r-1}`,`${q-1} remainder ${r}`],'Remainder must be less than divisor.',`${d} × ${q} = ${d*q}, leaving ${r}.`)}
  function decimal(){const m=R(0,6);if(m===0){const t=R(1,9),h=R(1,9),a=`0.${t}${h}`;return Q(`Write ${t} tenths and ${h} hundredths as a decimal.`,a,[a,`${t}.${h}`,`0.0${t+h}`,`${t+h}.0`],'Tenths first, then hundredths.',`${t}/10 + ${h}/100 = ${a}.`)}if(m===1){const w=R(1,20),h=R(1,99),a=`${w}.${String(h).padStart(2,'0')}`;return Q(`Which number is ${w} and ${h} hundredths?`,a,[a,`${w+h}.00`,`0.${h}`,`${w}.${h}0`],'Whole part comes before decimal point.',`The number is ${a}.`)}if(m===2){const w=R(10,99),t=R(1,9),h=R(1,9),v=`${w}.${t}${h}`;return Q(`What is the value of ${h} in ${v}?`,h/100,[h/100,h/10,h,h*10],'It is in the hundredths place.',`${h} hundredths = ${h/100}.`)}if(m===3){const a=R(100,999)/100,b=R(100,999)/100,ans=Math.max(a,b).toFixed(2);return Q(`Which is greater: ${a.toFixed(2)} or ${b.toFixed(2)}?`,ans,[a.toFixed(2),b.toFixed(2)],'Compare ones, tenths, then hundredths.',`${ans} is greater.`)}if(m===4){const v=R(101,999)/100,a=(Math.round(v*10)/10).toFixed(1);return Q(`Round ${v.toFixed(2)} to the nearest tenth.`,a,[a,v.toFixed(2),(Math.floor(v*10)/10).toFixed(1),Math.ceil(v).toFixed(1)],'Look at the hundredths digit.',`${v.toFixed(2)} rounds to ${a}.`)}if(m===5){const a=R(100,999)/100,b=R(10,499)/100;return Q(`${a.toFixed(2)} + ${b.toFixed(2)} = ?`,(a+b).toFixed(2),[(a+b).toFixed(2),Math.abs(a-b).toFixed(2),(a+b+1).toFixed(2),a.toFixed(2)],'Align decimal points.',`The sum is ${(a+b).toFixed(2)}.`)}const a=R(300,999)/100,b=R(100,299)/100;return Q(`${a.toFixed(2)} − ${b.toFixed(2)} = ?`,(a-b).toFixed(2),[(a-b).toFixed(2),(a+b).toFixed(2),(a-b+.1).toFixed(2),b.toFixed(2)],'Align decimal points.',`The difference is ${(a-b).toFixed(2)}.`)}
  function equation(){const m=R(0,5);if(m===0){const x=R(2,20),b=R(3,15);return Q(`x + ${b} = ${x+b}. Find x.`,x,nums(x,1,0),'Undo addition with subtraction.',`${x+b} − ${b} = ${x}.`)}if(m===1){const f=R(2,9),x=R(2,12);return Q(`${f} × □ = ${f*x}. Find □.`,x,nums(x,1,0),'Use division.',`${f*x} ÷ ${f} = ${x}.`)}if(m===2){const x=R(2,20),r=R(2,8);return Q(`Rule: multiply by ${r}. Input ${x}. Output?`,x*r,nums(x*r,r,0),'Apply the function rule.',`${x} × ${r} = ${x*r}.`)}if(m===3){const x=R(1,9),y=2*x+1;return Q(`Rule y = 2x + 1. Which pair is correct for x=${x}?`,`(${x}, ${y})`,[`(${x}, ${y})`,`(${y}, ${x})`,`(${x}, ${2*x})`,`(${x+1}, ${y})`],'Substitute x, then write (x,y).',`y=${y}, so (${x}, ${y}).`)}if(m===4){const a=R(2,15),b=R(2,15);return Q(`Which symbol makes ${a+b} __ ${a} + ${b} true?`,'=',['=','>','<','×'],'Calculate both sides.','Both sides are equal.')}const a=R(2,9),b=R(2,9),c=R(2,6);return Q(`Evaluate (${a}+${b}) × ${c}.`,(a+b)*c,[(a+b)*c,a+b*c,a*b+c,a+b+c],'Do parentheses first.',`${a}+${b}=${a+b}; ${a+b}×${c}=${(a+b)*c}.`)}
  const gens={placevalue:place,addsubconcepts:concepts,addition:addsub,multiplication:multiply,division:divide,measurement:measure,data:stats,fractionconcepts:fractionConcept,fractionoperations:fractionOps,geometry,perimeterarea:perimeter,division2digit:divideTwo,decimals:decimal,equations:equation};
  function make(topic){const id=topic==='mixed'||!gens[topic]?P(Object.keys(gens)):topic;return gens[id]()}
  window.TY_YEAR4={topics,question:make};
  if(window.TY_YEARS345){window.TY_YEARS345.topics['4']=topics;const old=window.TY_YEARS345.question;window.TY_YEARS345.question=(grade,topic)=>String(grade)==='4'?make(topic):old(grade,topic)}
})();
